service: serverless-express

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}

package:
  exclude:
    - .git/**
    - test/**
    - README.md

functions:
  serverless-express:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"

plugins:
  - serverless-offline
